### ISSUE TITLE
[UI] Home 엔티티 데이터 모델링 및 Cell 선택시 작업 처리

### ISSUE THREAD

**Issue by Damagucci-Juice** [Damagucci-Juice/sidedish#17]
## 💡 issue
- 셀을 구체적으로 넣어 봅시다. 뱃지 뷰는 어떻게 하면 좋을까요? 팩토리 메서드 패턴으로 해결하고 싶네요! 
- DishCell.configure(image:UIImage, ....) { } 여기에 매개변수로 전달할 적절한 타입을 선언한다면 무엇을 하면 좋을까요?
  - DTO 자체를 쓰는 것은 어떨까요 ~~용가리?~~
  - Detail Hash 값을 지정하는 것이 좋을까요? ~~구르트 아주머니 감사합니다 ^_^~~

## 📝 todo
- [ ] 모델 구현
  - [ ] Repository
  - [ ] Data Translate Object

- [ ]  뱃지 뷰( .런칭특가 || .이벤트특가 || .none) 를 팩토리 메서드 패턴으로 구현
- [ ] Collection View Cell 이 선택 되었을 때 처리할 일(Detail Hash 필드를 ID 처럼 써서 
  - [ ] Detail Page View 를 DetailViewController(hash: String) 으로 수정? 다른 방법이 있다면 추후 수정 (솔과 논의)
 
- [ ] 레포지터리 - 뷰모델의 구조를 어떻게 가져갈지 정의
  - [ ] URL 주소를 매번 스트링 값의 변화를 주면서 테스트 하지 말고 모듈에 환경 변수 값으로 지정하는 방법 도입(엔드포인트 분리?)

## 작업 분류
- 기능 구현

**Comment by Hansolkkim** [comment]
구찌 제가 서버로부터 오는 JSON 살펴봤는데,
저는 뱃지뷰로 설정을 최대 1개만 설정하는 거라 생각해서 지금 상태처럼 DiscountType 이라는 타입을 사용하도록 했는데 실제로 뱃지뷰가 여러개인 상품도 있더라구요,, 그래서 구찌가 말씀하신 방법대로 팩토리 메서드 패턴 방향으로 생각해봐야겠어요!
