### ISSUE TITLE
[UI] DetailView 마무리 작업

### ISSUE THREAD

**Issue by Hansolkkim** [Damagucci-Juice/sidedish#19]
## 💡 issue
- DetailView의 actionMethod를 정의해주는 작업을 진행합니다.

## 📝 todo
- [x] (주말진행사항) 최상단 이미지뷰를 ScollView에 넣을때 발생하는 이슈 해결
- [x] amountLabel(주문 수량을 나타내는 Label)과 amountStepper, totalPriceLabel, normalPriceLabel을 연결시키기
  - [x] normalPriceLabel의 text를 parsing하는 로직 구현
  - [x] (normalPriceLabel.text) * (amountLabel.text) 의 결과값에 천단위마다 `,`를 붙이고 마지막에 `원` 을 붙여 원하는 모습으로 totalPriceLabel.text에 들어갈 수 있도록 구현

## 작업 분류
- 기능 구현
