### ISSUE TITLE
[모델링] DetailView와 관련된 모델 구현

### ISSUE THREAD

**Issue by Hansolkkim** [Damagucci-Juice/sidedish#21]
## 💡 issue
- DetailView와 관련된 Entity, Repository, ViewModel을 구현합니다.

## 📝 todo
- [x] Dish의 Detail을 처리하는 Entity 구현 (DishDetail)
  - [x] 해당 Entity에서 data에 해당하는 Entity도 구현 (DetailData)
- [x] ViewModel의 지시로 네트워크 통신을 진행할 Repository 구현 (DishDetailRepository)
- [x] 해당 Repository를 소유할 ViewModel 구현 (DishDetailViewModel)

## 작업 분류
- 기능 구현
