### ISSUE TITLE
[Refactor] DetailView/ DetailViewController 리팩토링

### ISSUE THREAD

**Issue by Hansolkkim** [Damagucci-Juice/sidedish#24]
## 💡 issue
- 과도하게 커진 DetailView, DetailViewController의 코드를 리팩토링합니다.

## 📝 todo
- [x] DetailView의 코드 길이를 줄입니다.
  - [x] DetailView를 나눠서 구현합니다.
- [x] DetailViewController의 메소드를 분리합니다.

## 작업 분류
- 리펙터링

**Comment by Damagucci-Juice** [comment]
힘내세요 솔! 전 우주가 응원하고 있습니다!
