### ISSUE TITLE
[Refactor] 코드 리뷰 반영

### ISSUE THREAD

**Issue by Hansolkkim** [Damagucci-Juice/sidedish#26]
## 💡 issue
- 코드 리뷰 내용을 반영합니다.

## 📝 todo
- [x] DetailViewModel의 onUpdate 변수들을 설정할 때 viewModel의 optional binding을 제거 (guard let 사용)
- [x] PaddingLabel의 Inset을 설정해주는 메소드 선언
- [x] DishDetailViewModel이 많은 프로퍼티를 줄여주기
- [x] 네트워크 통신시 사용되는 url을 완성시켜주는 열거형 추가
- [x] Product 클래스의 discountType 프로퍼티를 초기화해주는 로직 수정
- [x] 데이터를 fetch 해오는 과정에서 view Model 의 역할을 명확하게 정리
- [ ] Repository, viewModel, CellFactory 등 데이터를 가져오는 부분에서 공통되는 부분 Protocol 로 추상화

## 작업 분류
- 리펙터링
## 💡 issue
- 코드 리뷰 내용을 반영합니다.
