### ISSUE TITLE
[UI] DishCell 에 이미지를 담기 작업

### ISSUE THREAD

**Issue by Damagucci-Juice** [Damagucci-Juice/sidedish#27]
## 💡 issue
- HomeVC 의 CollectionView 의 Cell 에 이미지를 넣는 작업을 합니다.

## 📝 todo
- [ ] Cell에 URL 주소만 분리해서 Image fetch
- [ ] 다 fetch 해오면 한꺼번에 update(요구사항은 사진별로 업뎃이지만 그냥 진행)
- [ ] model, ViewModel 에서 UIKit 안쓰는 연습 (Data 타입사용)

## 작업 분류
- 기능 구현
