### ISSUE TITLE
[UI] Home 화면 컨셉 구현

### ISSUE THREAD

**Issue by Damagucci-Juice** [Damagucci-Juice/sidedish#3]
## 💡 issue
- 홈 화면의 대략적인 구현을 합니다. 

## 📝 todo
- [x] `dev` 브랜치에 "SF Pro Display" 폰트 도입
- [x] 네비게이션 컨트롤러 구현
- [x] 네비게이션 컨드롤러 헤더 구현
- [x] CollectionView 작업
- [ ] Collection View Header View 구현
    ㄴ 개별 셀의 디테일 보단, Section 과 Row를 어떻게 분리할지에 초점을 두고 작업
    ㄴ 각 Section 마다 Cell 의 배경색을 구분(예: ([1 섹션:  초록, 2 섹션 : 빨강, 3 섹션: 노랑])

## 작업 분류
- 기능 구현
