### ISSUE TITLE
[UI] CollectionView Cell 의 나타나는 방향 설정 및 초기 모델링 작업

### ISSUE THREAD

**Issue by Damagucci-Juice** [Damagucci-Juice/sidedish#7]
## 💡 issue
- cell 수직 방향으로 나타나게끔 설정
- 초기 모델을 `HomeViewController.swift`에 작성

## 📝 todo
- [x] #12
- [ ] 반찬 데이터를 가져오는 파일 생성
- [ ] Section Header View를 요구사항에 맞춰 설정
- [ ] CollectionView Cell 의 크기를 조정
- [ ] Cell 사이 거리 조정
- [ ] Cell 모서리 둥글기 조정

## 작업 분류
- 기능 구현
