### ISSUE TITLE
[UI] DetailView 구현

### ISSUE THREAD

**Issue by Hansolkkim** [Damagucci-Juice/sidedish#8]
## 💡 issue
- CollectionView의 cell을 누르면 나올 DetailView를 `코드로` 구현합니다.

## 📝 todo
- [x] 커스텀 폰트 적용
- [x] 상하좌우 Padding이 있는 PaddingLabel 구현
- [x] 제일 바깥 화면을 UIScrollView로 구현
- [x] UIScrollView 내의 첫 이미지를 UIScrollView로 구현
- [x] 데이터를 받아오기 전에도 보여줄 수 있는 부분을 구현해놓기

## 작업 분류
- 기능 구현
