### ISSUE TITLE
[Refactoring]  첫 번째 코드 리뷰 반영

### ISSUE THREAD

**Issue by Hansolkkim** [Damagucci-Juice/sidedish#9]
## 💡 issue
- [첫 번째 코드 리뷰](https://github.com/codesquad-members-2022/sidedish/pull/14)의 내용을 반영합니다.

## 📝 todo
- [x] 불필요한 공백 제거하기
- [ ] DishCell의 `configure()` 메소드의 파라미터 갯수 줄이는 방법 생각해보고 수정하기
- [x] `collectionView(_:cellForItem:)` 메소드에서 cell의 identifier를 입력해줄 때, String으로 직접 하드코딩(타이핑)할 때 생길 수 있는 문제가 무엇이 있을지 의견 공유
- [x] MVVM을 선택한 이유에 대해 의견 공유

## 작업 분류
- 리펙터링
